### PR TITLE
update repositories recursively int sub directories.

### PR DESCRIPTION
**Pull request by kadeemding**

### CODE REVIEW

**Comment by earwig** [comment]
This is a good idea, thank you for the patch. However, I've decided to implement it in a different way; your solution works well when the base directory only contains git repos, but can produce a lot of error messages if it has other things.

**Comment by kadeemding** [comment]
Thank you! I've took your implementation.

**Comment by mikerogerz** [comment]
Shouldn't this enabled via a flag?

**Comment by earwig** [comment]
You're right @mikerogerz, I was a bit lazy in the first pass. Added `--depth` in cc0254d60d66776244b87331af1a2a333f3e4c3c. I kept a low-but-nonzero max depth by default since it matches the spirit of the original behavior. I'm open to being convinced that the default should be lower/higher...

**Pull request closed without merging**
